import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Drives the app's official UI locale (static strings served via
/// `AppLocalizations`, generated by `flutter gen-l10n`).
///
/// This is intentionally separate from `LanguageService`, which controls
/// the language used for AI-translated dynamic content (disease info,
/// chatbot replies) and is untouched by this provider.
class LocaleProvider {
  LocaleProvider._();

  static const _prefsKey = 'app_locale';

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ur'),
  ];

  static final ValueNotifier<Locale> locale =
      ValueNotifier(supportedLocales.first);

  /// Loads the persisted locale, if any. Call once before `runApp`.
  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_prefsKey);
    if (code == null) return;
    for (final l in supportedLocales) {
      if (l.languageCode == code) {
        locale.value = l;
        return;
      }
    }
  }

  static Future<void> setLocale(Locale newLocale) async {
    if (!supportedLocales.contains(newLocale)) return;
    locale.value = newLocale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, newLocale.languageCode);
  }
}
